export const typeOfDiets : string[] = ['Normal' , 'Mediterranean', 'Ketogenic', 'Vegetarian', 'Vegan', 'Paleo', 'Gluten-Free', 'Dairy-Free', 'Low-Fat', 'Low-Carbohydrate', 'Intermittent Fasting']

export const typeDescriptions = [
  'Anything special.',
  'It focuses on fresh and natural foods like fruits, vegetables, fish, nuts, seeds, olive oil, and low-fat dairy products.',
  'It is a low-carbohydrate, high-fat diet used for weight loss and improved metabolic health.',
  'It excludes all animal products and is based on foods such as vegetables, fruits, whole grains, legumes, and nuts.',
  'Similar to a vegetarian diet, but it completely excludes all animal products, including dairy, eggs, and honey.',
  'It is based on foods that are believed to have been consumed during the Paleolithic era, such as meat, fish, fruits, vegetables, and nuts.',
  'It excludes any food containing gluten, such as wheat, barley, and rye, and focuses on alternatives like rice, quinoa, and corn.',
  'It eliminates all dairy products, such as milk, cheese, and butter, and focuses on alternative sources of calcium, like broccoli and almonds.',
  'It focuses on limiting fat intake, especially saturated fats, and is based on foods like fruits, vegetables, and whole grains.',
  'It focuses on limiting carbohydrate intake and relies on protein and fat-rich foods like meat, fish, eggs, and avocados.',
  'It involves alternating periods of fasting with periods of regular eating and can be effective for weight loss and improving metabolic health.'
]

export const pricesForm : string[] = ['Cheap', 'Normal', 'Expensive'];

export const sizesForm : string[] = ['Average','Skinny', 'Overweight', 'Prefer not to say'];

export const goalsForm : string[] = [
  'Any',
  "Weight loss",
  "Improved metabolic health",
  "Developing healthier eating habits",
  "Increased energy",
  "Enhanced athletic performance",
  "Promoting cardiovascular health"
];

export const countries = [
    'Other',
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo (Brazzaville)",
    "Congo (Kinshasa)",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "East Timor",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Ivory Coast",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Korea North",
    "Korea South",
    "Kosovo",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macedonia",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestinian Territories",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Swaziland",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Vatican City",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe"
  ];
  